name 'blp-gemrc'
maintainer 'Bloomberg Infrastructure Engineering'
maintainer_email 'chef@bloomberg.net'
license 'Apache 2.0'
description 'Library cookbook which manages a RubyGems configuration file.'
long_description 'Library cookbook which manages a RubyGems configuration file.'
version '1.0.0'
source_url 'https://github.com/bloomberg/blp-gemrc-cookbook'
issues_url 'https://github.com/bloomberg/blp-gemrc-cookbook'

depends 'poise', '~> 2.2'
